version: 1
datastore:
  user: roger
  password: 
  hostname: acit3855-kafka.westus.cloudapp.azure.com
  port: 3306
  db: events
events:
  hostname: acit3855-kafka.westus.cloudapp.azure.com
  port: 9092
  topic: events
